### PR TITLE
OY2-19471: Total Rate Label Updates

### PR DESCRIPTION
**Pull request by karla-vm**
## Purpose

Updating Total rate labels for AIF-HH and FUA-HH in FY2021 and FY2022.

Application endpoint: https://dkf6qf0bj40we.cloudfront.net/

#### Linked Issues to Close

Closes [OY2-19471](https://qmacbis.atlassian.net/browse/OY2-19471).

## Approach

Minor text changes.

## Learning

_Describe the research stage_

N/A

## Assorted Notes/Considerations

N/A

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

### CODE REVIEW

**Review by benjaminpaige — APPROVED** [review]
Woot!!

**Review by jphechter — APPROVED** [review]

**Review by benjaminpaige — APPROVED** [review]

**Review by benjaminpaige — CHANGES_REQUESTED** [review]
I think the only thing we want to change here is the `text` value.

**Comment by karla-vm** [comment]
> I think the only thing we want to change here is the `text` value.

Fixed! Pushing now.

**Review by benjaminpaige — APPROVED** [review]

**Comment by karla-vm** [comment]
@benjaminpaige we needed to update the `label` field as well as the `text` field for the OMS total rate labels to show up correctly! I pushed a fix now.

**Review by gmrabian — APPROVED** [review]

**Pull request merged**
