### PR TITLE
Idle Timeout

### PR DESCRIPTION
**Pull request by benjaminpaige**
## Purpose

Implements a timeout when on a measure that will save after 55 mins of inactivity and notify user they will be logged out. After another 5 mins user will. be logged out and redirected to home screen. 

#### Linked Issues to Close

https://qmacbis.atlassian.net/browse/OY2-16945

## Assorted Notes/Considerations

Users will be warned at 55 minutes of idle time that they will be logged out when in a measure.
All entered form data will be automatically saved.
Users will be logged out of the system after 1 hour of idle time.
Users will be logged out of the system after 12 hours no matter what. (Cognito setting)
Scrolling, key presses, clicking, etc. will reset the idle time clock.

#### Pull Request Creator Checklist

- [x] This PR has an associated issue or issues.
- [x] The associated issue(s) are linked above.
- [x] This PR meets all acceptance criteria for those issues.
- [x] This PR and linked issue(s) are adequately documented
- [x] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [x] Someone has been assigned this PR.
- [x] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

### CODE REVIEW

**Review by jdinh8124 — APPROVED** [review]
Looks all good to me

**Review by abelzer212 — DISMISSED** [review]

**Comment by abelzer212** [comment]
The timeout doesn't work on the CoreSet Page

**Comment by abelzer212** [comment]
The timeout also doesn't work on the Measure List page

**Comment by abelzer212** [comment]
The timeout also doesn't work on the qualifiers

**Comment by abelzer212** [comment]
Timeout also doesn't work on the coreset creation page

**Pull request merged**
